### ISSUE TITLE
Thanks for trying.

### ISSUE THREAD

**Issue by BlackStar-EoP** [atsushieno/ADLplug-AE#2]
This POS doesn't compile at all under VS2022. Also I disagree with the "herp derp I don't want to alter the code."
That's what a fork is for

Cya around

**Comment by atsushieno** [comment]
Thanks for reporting. I don't use Windows on my daily basis, but if you can share the build failure logs I can guess what happens and/or try to fix.

**Comment by BlackStar-EoP** [comment]
I've fixed it in my own repository, I've forked yours and forked ADLplug and pointed the submodule to my own.
Your patch file is applied and I've committed the output of cmake.

Fixes include:
- manual defines of M_PI (nonstandard), can be fixed by setting up CRT math inside VS but cba to setup all this, plus every run of cmake will mess up the project files and I really don't want to look into how to set all this up.
- nonstandard array initialization fixed
- undef of min macro due to MS' idiotic way of defining this and breaking std::min (most likely fixable via cmake as well)
- rename of wopl/wopn.c to cpp due to again MS' idiotic way of trying to detect cpp compiler and breaking on that.
- removal of tests on __cplusplus version, absolutely unnecessary on c++17 compilers, probably again fixable in cmake files

Won't fix: a gazillion amount of compiler warnings

Future plans:
- Better way of visualizing the 2OP/4OP algorithms
- export to VGM

**Comment by atsushieno** [comment]
Awesome, thanks for the updates. I would close the issue. In the future people (including myself) could migrate to your version of codebase. (I kinda needed it for my own Android plugin stuff, but there is no reason to not switch to yours.)

**Comment by BlackStar-EoP** [comment]
Oh dear, it seems I'm the maintainer of a VST now 😂
